# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.srcs/sources_1/ip/output_1b/output_1b.xci
# IP: The module: 'output_1b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.gen/sources_1/ip/output_1b/output_1b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_1b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.srcs/sources_1/ip/output_1b/output_1b.xci
# IP: The module: 'output_1b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.gen/sources_1/ip/output_1b/output_1b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_1b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
