C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unisims_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unisims_ver C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unisims_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlog -source -work unisims_ver -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unisims_ver/.cxl.verilog.unisim.unisims_ver.nt64.cmf
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlog -source -sv -svinputport=relaxed -work unisims_ver -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unisims_ver/.cxl.systemverilog.unisim.unisims_ver.nt64.cmf
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unimacro_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unimacro_ver C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unimacro_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlog -source -work unimacro_ver -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unimacro_ver/.cxl.verilog.unimacro.unimacro_ver.nt64.cmf
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unifast_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unifast_ver C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unifast_ver
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlog -source -work unifast_ver -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unifast_ver/.cxl.verilog.unifast.unifast_ver.nt64.cmf
