######################################################################
#
# File name : basic_nn_tb_simulate.do
# Created on: Tue Mar 28 16:05:24 -0600 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.basic_nn_tb

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {basic_nn_tb_wave.do}

view wave
view structure
view signals

do {basic_nn_tb.udo}

run 1000ns
