######################################################################
#
# File name : basic_nn_tb_wave.do
# Created on: Tue Mar 28 16:05:24 -0600 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
