######################################################################
#
# File name : basic_nn_tb_compile.do
# Created on: Tue Mar 28 16:05:20 -0600 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/af_relu.vhd" \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/af_sigmoid.vhd" \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/af_tanh.vhd" \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/dense_sigmoid.vhd" \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/gru.vhd" \

vcom  -2008 -work xil_defaultlib  \
"../../../../../../../../../GitHub/FEC_Raytheon2022/NN VHDL/basic_nn_tb.vhd" \

quit -force

