######################################################################
#
# File name : tb_mem_compile.do
# Created on: Tue Mar 28 14:28:53 -0600 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../NeuralNet.gen/sources_1/ip/InitMem/sim/InitMem.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../NeuralNet.srcs/sim_1/new/tb_mem.vhd" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

