######################################################################
#
# File name : tb_mem_wave.do
# Created on: Wed Mar 15 11:54:38 -0600 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
