C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unisim
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unisim C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unisim
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vcom -source -93 -work unisim -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unisim/.cxl.vhdl.unisim.unisim.nt64.cmf -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unisim/.cxl.vhdl.secureip_vhdl_unisim.unisim.nt64.cmf
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unimacro
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unimacro C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unimacro
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vcom -source -93 -work unimacro -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unimacro/.cxl.vhdl.unimacro.unimacro.nt64.cmf
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vlib C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unifast
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vmap unifast C:/Users/18019/Documents/UofU/SPRING2023/capstoneProject/MemoryVHDL/NeuralNet/NeuralNet.cache/compile_simlib/modelsim/unifast
C:/intelFPGA_lite/18.1/modelsim_ase/win32aloem/vcom -source -93 -work unifast -f C:\Users\18019\Documents\UofU\SPRING2023\capstoneProject\MemoryVHDL\NeuralNet\NeuralNet.cache\compile_simlib\modelsim/unifast/.cxl.vhdl.unifast.unifast.nt64.cmf
